// Code generated by protoc-gen-go. DO NOT EDIT.
// source: node.proto

/*
Package go_micro_srv_v1_node is a generated protocol buffer package.

It is generated from these files:
	node.proto

It has these top-level messages:
	NodeReq
	LiAttr
	NodeRsp
	NodeInfo
*/
package go_micro_srv_v1_node

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type NodeReq struct {
	ParentId string `protobuf:"bytes,1,opt,name=parentId" json:"parentId,omitempty"`
	Guid     string `protobuf:"bytes,2,opt,name=guid" json:"guid,omitempty"`
	Type     string `protobuf:"bytes,3,opt,name=type" json:"type,omitempty"`
}

func (m *NodeReq) Reset()                    { *m = NodeReq{} }
func (m *NodeReq) String() string            { return proto.CompactTextString(m) }
func (*NodeReq) ProtoMessage()               {}
func (*NodeReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *NodeReq) GetParentId() string {
	if m != nil {
		return m.ParentId
	}
	return ""
}

func (m *NodeReq) GetGuid() string {
	if m != nil {
		return m.Guid
	}
	return ""
}

func (m *NodeReq) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type LiAttr struct {
	Guid string `protobuf:"bytes,1,opt,name=guid" json:"guid,omitempty"`
	Type string `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`
}

func (m *LiAttr) Reset()                    { *m = LiAttr{} }
func (m *LiAttr) String() string            { return proto.CompactTextString(m) }
func (*LiAttr) ProtoMessage()               {}
func (*LiAttr) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *LiAttr) GetGuid() string {
	if m != nil {
		return m.Guid
	}
	return ""
}

func (m *LiAttr) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type NodeRsp struct {
	Children bool    `protobuf:"varint,1,opt,name=children" json:"children,omitempty"`
	Id       string  `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
	LiAttr   *LiAttr `protobuf:"bytes,3,opt,name=li_attr,json=liAttr" json:"li_attr,omitempty"`
	Parent   string  `protobuf:"bytes,4,opt,name=parent" json:"parent,omitempty"`
	Text     string  `protobuf:"bytes,5,opt,name=text" json:"text,omitempty"`
	Type     string  `protobuf:"bytes,6,opt,name=type" json:"type,omitempty"`
}

func (m *NodeRsp) Reset()                    { *m = NodeRsp{} }
func (m *NodeRsp) String() string            { return proto.CompactTextString(m) }
func (*NodeRsp) ProtoMessage()               {}
func (*NodeRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *NodeRsp) GetChildren() bool {
	if m != nil {
		return m.Children
	}
	return false
}

func (m *NodeRsp) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *NodeRsp) GetLiAttr() *LiAttr {
	if m != nil {
		return m.LiAttr
	}
	return nil
}

func (m *NodeRsp) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *NodeRsp) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *NodeRsp) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type NodeInfo struct {
	Id         string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	LoginId    string   `protobuf:"bytes,2,opt,name=login_id,json=loginId" json:"login_id,omitempty"`
	AuthMethod string   `protobuf:"bytes,3,opt,name=auth_method,json=authMethod" json:"auth_method,omitempty"`
	Type       string   `protobuf:"bytes,4,opt,name=type" json:"type,omitempty"`
	Role       []string `protobuf:"bytes,5,rep,name=role" json:"role,omitempty"`
	Name       string   `protobuf:"bytes,6,opt,name=name" json:"name,omitempty"`
	Email      string   `protobuf:"bytes,7,opt,name=email" json:"email,omitempty"`
	State      string   `protobuf:"bytes,8,opt,name=state" json:"state,omitempty"`
	Gender     string   `protobuf:"bytes,9,opt,name=gender" json:"gender,omitempty"`
	Rank       string   `protobuf:"bytes,10,opt,name=rank" json:"rank,omitempty"`
}

func (m *NodeInfo) Reset()                    { *m = NodeInfo{} }
func (m *NodeInfo) String() string            { return proto.CompactTextString(m) }
func (*NodeInfo) ProtoMessage()               {}
func (*NodeInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *NodeInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *NodeInfo) GetLoginId() string {
	if m != nil {
		return m.LoginId
	}
	return ""
}

func (m *NodeInfo) GetAuthMethod() string {
	if m != nil {
		return m.AuthMethod
	}
	return ""
}

func (m *NodeInfo) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *NodeInfo) GetRole() []string {
	if m != nil {
		return m.Role
	}
	return nil
}

func (m *NodeInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NodeInfo) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *NodeInfo) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *NodeInfo) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

func (m *NodeInfo) GetRank() string {
	if m != nil {
		return m.Rank
	}
	return ""
}

func init() {
	proto.RegisterType((*NodeReq)(nil), "go.micro.srv.v1.node.NodeReq")
	proto.RegisterType((*LiAttr)(nil), "go.micro.srv.v1.node.LiAttr")
	proto.RegisterType((*NodeRsp)(nil), "go.micro.srv.v1.node.NodeRsp")
	proto.RegisterType((*NodeInfo)(nil), "go.micro.srv.v1.node.NodeInfo")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Node service

type NodeClient interface {
	NodeIndex(ctx context.Context, in *NodeReq, opts ...client.CallOption) (*NodeRsp, error)
	NodeChildren(ctx context.Context, in *NodeReq, opts ...client.CallOption) (Node_NodeChildrenClient, error)
	NodeRead(ctx context.Context, in *NodeReq, opts ...client.CallOption) (*NodeInfo, error)
	NodeSave(ctx context.Context, in *NodeInfo, opts ...client.CallOption) (*NodeInfo, error)
	NodePatch(ctx context.Context, in *NodeInfo, opts ...client.CallOption) (*NodeInfo, error)
	NodeDelete(ctx context.Context, in *NodeReq, opts ...client.CallOption) (*NodeRsp, error)
}

type nodeClient struct {
	c           client.Client
	serviceName string
}

func NewNodeClient(serviceName string, c client.Client) NodeClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "go.micro.srv.v1.node"
	}
	return &nodeClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *nodeClient) NodeIndex(ctx context.Context, in *NodeReq, opts ...client.CallOption) (*NodeRsp, error) {
	req := c.c.NewRequest(c.serviceName, "Node.NodeIndex", in)
	out := new(NodeRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) NodeChildren(ctx context.Context, in *NodeReq, opts ...client.CallOption) (Node_NodeChildrenClient, error) {
	req := c.c.NewRequest(c.serviceName, "Node.NodeChildren", &NodeReq{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &nodeNodeChildrenClient{stream}, nil
}

type Node_NodeChildrenClient interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*NodeRsp, error)
}

type nodeNodeChildrenClient struct {
	stream client.Streamer
}

func (x *nodeNodeChildrenClient) Close() error {
	return x.stream.Close()
}

func (x *nodeNodeChildrenClient) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *nodeNodeChildrenClient) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *nodeNodeChildrenClient) Recv() (*NodeRsp, error) {
	m := new(NodeRsp)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *nodeClient) NodeRead(ctx context.Context, in *NodeReq, opts ...client.CallOption) (*NodeInfo, error) {
	req := c.c.NewRequest(c.serviceName, "Node.NodeRead", in)
	out := new(NodeInfo)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) NodeSave(ctx context.Context, in *NodeInfo, opts ...client.CallOption) (*NodeInfo, error) {
	req := c.c.NewRequest(c.serviceName, "Node.NodeSave", in)
	out := new(NodeInfo)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) NodePatch(ctx context.Context, in *NodeInfo, opts ...client.CallOption) (*NodeInfo, error) {
	req := c.c.NewRequest(c.serviceName, "Node.NodePatch", in)
	out := new(NodeInfo)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) NodeDelete(ctx context.Context, in *NodeReq, opts ...client.CallOption) (*NodeRsp, error) {
	req := c.c.NewRequest(c.serviceName, "Node.NodeDelete", in)
	out := new(NodeRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Node service

type NodeHandler interface {
	NodeIndex(context.Context, *NodeReq, *NodeRsp) error
	NodeChildren(context.Context, *NodeReq, Node_NodeChildrenStream) error
	NodeRead(context.Context, *NodeReq, *NodeInfo) error
	NodeSave(context.Context, *NodeInfo, *NodeInfo) error
	NodePatch(context.Context, *NodeInfo, *NodeInfo) error
	NodeDelete(context.Context, *NodeReq, *NodeRsp) error
}

func RegisterNodeHandler(s server.Server, hdlr NodeHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&Node{hdlr}, opts...))
}

type Node struct {
	NodeHandler
}

func (h *Node) NodeIndex(ctx context.Context, in *NodeReq, out *NodeRsp) error {
	return h.NodeHandler.NodeIndex(ctx, in, out)
}

func (h *Node) NodeChildren(ctx context.Context, stream server.Streamer) error {
	m := new(NodeReq)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.NodeHandler.NodeChildren(ctx, m, &nodeNodeChildrenStream{stream})
}

type Node_NodeChildrenStream interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*NodeRsp) error
}

type nodeNodeChildrenStream struct {
	stream server.Streamer
}

func (x *nodeNodeChildrenStream) Close() error {
	return x.stream.Close()
}

func (x *nodeNodeChildrenStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *nodeNodeChildrenStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *nodeNodeChildrenStream) Send(m *NodeRsp) error {
	return x.stream.Send(m)
}

func (h *Node) NodeRead(ctx context.Context, in *NodeReq, out *NodeInfo) error {
	return h.NodeHandler.NodeRead(ctx, in, out)
}

func (h *Node) NodeSave(ctx context.Context, in *NodeInfo, out *NodeInfo) error {
	return h.NodeHandler.NodeSave(ctx, in, out)
}

func (h *Node) NodePatch(ctx context.Context, in *NodeInfo, out *NodeInfo) error {
	return h.NodeHandler.NodePatch(ctx, in, out)
}

func (h *Node) NodeDelete(ctx context.Context, in *NodeReq, out *NodeRsp) error {
	return h.NodeHandler.NodeDelete(ctx, in, out)
}

func init() { proto.RegisterFile("node.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 428 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x94, 0x5f, 0x8e, 0xd3, 0x30,
	0x10, 0xc6, 0x37, 0xfd, 0x93, 0xa4, 0xb3, 0x88, 0x07, 0x6b, 0x85, 0xcc, 0x8a, 0x3f, 0xab, 0x3c,
	0xf1, 0x14, 0x2d, 0x8b, 0x38, 0x00, 0x82, 0x97, 0x6a, 0x5b, 0xb4, 0x0a, 0x07, 0xa8, 0x4c, 0x3d,
	0x24, 0x16, 0x89, 0x1d, 0x1c, 0x6f, 0x55, 0xee, 0xc4, 0x95, 0xb8, 0x00, 0xa7, 0x40, 0x63, 0x07,
	0xb3, 0x0f, 0x85, 0x45, 0x2a, 0x6f, 0xf3, 0x7d, 0xae, 0xbf, 0xf9, 0xcd, 0xb8, 0x0a, 0x80, 0x36,
	0x12, 0xcb, 0xde, 0x1a, 0x67, 0xd8, 0x59, 0x6d, 0xca, 0x4e, 0x6d, 0xad, 0x29, 0x07, 0xbb, 0x2b,
	0x77, 0x2f, 0x4b, 0x3a, 0x2b, 0xd6, 0x90, 0xbd, 0x37, 0x12, 0x2b, 0xfc, 0xc2, 0xce, 0x21, 0xef,
	0x85, 0x45, 0xed, 0x96, 0x92, 0x27, 0x17, 0xc9, 0x8b, 0x45, 0x15, 0x35, 0x63, 0x30, 0xab, 0x6f,
	0x95, 0xe4, 0x13, 0xef, 0xfb, 0x9a, 0x3c, 0xf7, 0xb5, 0x47, 0x3e, 0x0d, 0x1e, 0xd5, 0xc5, 0x25,
	0xa4, 0x2b, 0xf5, 0xc6, 0x39, 0x1b, 0x6f, 0x24, 0x07, 0x6e, 0x4c, 0xee, 0xdc, 0xf8, 0x96, 0x8c,
	0x04, 0x43, 0x4f, 0x04, 0xdb, 0x46, 0xb5, 0xd2, 0xa2, 0xf6, 0xf7, 0xf2, 0x2a, 0x6a, 0xf6, 0x10,
	0x26, 0xb1, 0xff, 0x44, 0x49, 0xf6, 0x1a, 0xb2, 0x56, 0x6d, 0x84, 0x73, 0xd6, 0x03, 0x9c, 0x5e,
	0x3d, 0x29, 0x0f, 0x0d, 0x58, 0x06, 0x9c, 0x2a, 0x6d, 0x03, 0xd6, 0x23, 0x48, 0xc3, 0x50, 0x7c,
	0xe6, 0xa3, 0x46, 0xe5, 0xd1, 0x70, 0xef, 0xf8, 0x7c, 0x44, 0xc3, 0xbd, 0x8b, 0xb8, 0xe9, 0x1d,
	0xdc, 0x1f, 0x09, 0xe4, 0x84, 0xbb, 0xd4, 0x9f, 0xcc, 0xc8, 0x94, 0x44, 0xa6, 0xc7, 0x90, 0xb7,
	0xa6, 0x56, 0x7a, 0x13, 0x49, 0x33, 0xaf, 0x97, 0x92, 0x3d, 0x87, 0x53, 0x71, 0xeb, 0x9a, 0x4d,
	0x87, 0xae, 0x31, 0x72, 0xdc, 0x19, 0x90, 0xb5, 0xf6, 0x4e, 0x6c, 0x36, 0xfb, 0xdd, 0x8c, 0x3c,
	0x6b, 0x5a, 0xe4, 0xf3, 0x8b, 0x29, 0x79, 0x54, 0x93, 0xa7, 0x45, 0x17, 0xa1, 0xa8, 0x66, 0x67,
	0x30, 0xc7, 0x4e, 0xa8, 0x96, 0x67, 0xde, 0x0c, 0x82, 0xdc, 0xc1, 0x09, 0x87, 0x3c, 0x0f, 0xae,
	0x17, 0xb4, 0x80, 0x1a, 0xb5, 0x44, 0xcb, 0x17, 0x61, 0x01, 0x41, 0xf9, 0x5e, 0x42, 0x7f, 0xe6,
	0x10, 0x72, 0xa9, 0xbe, 0xfa, 0x3e, 0x85, 0x19, 0x0d, 0xcb, 0xae, 0x61, 0x11, 0x86, 0x96, 0xb8,
	0x67, 0x4f, 0x0f, 0x2f, 0x7a, 0xfc, 0x1b, 0x9d, 0xff, 0xed, 0x78, 0xe8, 0x8b, 0x13, 0x76, 0x03,
	0x0f, 0x48, 0xbc, 0xfd, 0xf5, 0xb2, 0x47, 0xe6, 0x5d, 0x26, 0xec, 0x3a, 0xbc, 0x49, 0x85, 0x42,
	0xde, 0x97, 0xf6, 0xec, 0xcf, 0xc7, 0xf4, 0xa4, 0xc5, 0x09, 0x5b, 0x85, 0xb0, 0x0f, 0x62, 0x87,
	0xec, 0x9e, 0x5f, 0xff, 0x43, 0xda, 0x3a, 0x6c, 0xee, 0x46, 0xb8, 0x6d, 0xf3, 0x1f, 0xe2, 0x56,
	0x00, 0xa4, 0xde, 0x61, 0x8b, 0x0e, 0x8f, 0xdd, 0xdc, 0xc7, 0xd4, 0x7f, 0x19, 0x5e, 0xfd, 0x0c,
	0x00, 0x00, 0xff, 0xff, 0x62, 0x16, 0xcb, 0x50, 0x27, 0x04, 0x00, 0x00,
}
