// Code generated by protoc-gen-go. DO NOT EDIT.
// source: account.proto

/*
Package go_micro_srv_v1_account is a generated protocol buffer package.

It is generated from these files:
	account.proto

It has these top-level messages:
	NodeReq
	LiAttr
	NodeRsp
*/
package go_micro_srv_v1_account

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type NodeReq struct {
	ParentId string `protobuf:"bytes,1,opt,name=parentId" json:"parentId,omitempty"`
	Guid     string `protobuf:"bytes,2,opt,name=guid" json:"guid,omitempty"`
	Type     string `protobuf:"bytes,3,opt,name=type" json:"type,omitempty"`
}

func (m *NodeReq) Reset()                    { *m = NodeReq{} }
func (m *NodeReq) String() string            { return proto.CompactTextString(m) }
func (*NodeReq) ProtoMessage()               {}
func (*NodeReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *NodeReq) GetParentId() string {
	if m != nil {
		return m.ParentId
	}
	return ""
}

func (m *NodeReq) GetGuid() string {
	if m != nil {
		return m.Guid
	}
	return ""
}

func (m *NodeReq) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type LiAttr struct {
	Guid string `protobuf:"bytes,1,opt,name=guid" json:"guid,omitempty"`
	Type string `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`
}

func (m *LiAttr) Reset()                    { *m = LiAttr{} }
func (m *LiAttr) String() string            { return proto.CompactTextString(m) }
func (*LiAttr) ProtoMessage()               {}
func (*LiAttr) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *LiAttr) GetGuid() string {
	if m != nil {
		return m.Guid
	}
	return ""
}

func (m *LiAttr) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type NodeRsp struct {
	Children bool    `protobuf:"varint,1,opt,name=children" json:"children,omitempty"`
	Id       string  `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
	LiAttr   *LiAttr `protobuf:"bytes,3,opt,name=li_attr,json=liAttr" json:"li_attr,omitempty"`
	Parent   string  `protobuf:"bytes,4,opt,name=parent" json:"parent,omitempty"`
	Text     string  `protobuf:"bytes,5,opt,name=text" json:"text,omitempty"`
	Type     string  `protobuf:"bytes,6,opt,name=type" json:"type,omitempty"`
}

func (m *NodeRsp) Reset()                    { *m = NodeRsp{} }
func (m *NodeRsp) String() string            { return proto.CompactTextString(m) }
func (*NodeRsp) ProtoMessage()               {}
func (*NodeRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *NodeRsp) GetChildren() bool {
	if m != nil {
		return m.Children
	}
	return false
}

func (m *NodeRsp) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *NodeRsp) GetLiAttr() *LiAttr {
	if m != nil {
		return m.LiAttr
	}
	return nil
}

func (m *NodeRsp) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *NodeRsp) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *NodeRsp) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func init() {
	proto.RegisterType((*NodeReq)(nil), "go.micro.srv.v1.account.NodeReq")
	proto.RegisterType((*LiAttr)(nil), "go.micro.srv.v1.account.LiAttr")
	proto.RegisterType((*NodeRsp)(nil), "go.micro.srv.v1.account.NodeRsp")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Account service

type AccountClient interface {
	NodeIndex(ctx context.Context, in *NodeReq, opts ...client.CallOption) (*NodeRsp, error)
}

type accountClient struct {
	c           client.Client
	serviceName string
}

func NewAccountClient(serviceName string, c client.Client) AccountClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "go.micro.srv.v1.account"
	}
	return &accountClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *accountClient) NodeIndex(ctx context.Context, in *NodeReq, opts ...client.CallOption) (*NodeRsp, error) {
	req := c.c.NewRequest(c.serviceName, "Account.NodeIndex", in)
	out := new(NodeRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Account service

type AccountHandler interface {
	NodeIndex(context.Context, *NodeReq, *NodeRsp) error
}

func RegisterAccountHandler(s server.Server, hdlr AccountHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&Account{hdlr}, opts...))
}

type Account struct {
	AccountHandler
}

func (h *Account) NodeIndex(ctx context.Context, in *NodeReq, out *NodeRsp) error {
	return h.AccountHandler.NodeIndex(ctx, in, out)
}

func init() { proto.RegisterFile("account.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 256 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0x31, 0x4f, 0xc3, 0x30,
	0x10, 0x85, 0x49, 0x28, 0x4e, 0x7b, 0x08, 0x06, 0x0f, 0x60, 0x75, 0xa1, 0xca, 0xc4, 0x64, 0x41,
	0x59, 0x58, 0x3b, 0x56, 0x02, 0x24, 0x32, 0x23, 0xa1, 0x10, 0x9f, 0x8a, 0xa5, 0x10, 0x1b, 0xe7,
	0x5a, 0x85, 0x5f, 0xc5, 0x5f, 0x44, 0xb1, 0x2d, 0xc3, 0x40, 0xd5, 0xed, 0xde, 0xb3, 0xdf, 0xf9,
	0x3b, 0x1f, 0x9c, 0xd5, 0x4d, 0x63, 0xb6, 0x1d, 0x49, 0xeb, 0x0c, 0x19, 0x7e, 0xb9, 0x31, 0xf2,
	0x43, 0x37, 0xce, 0xc8, 0xde, 0xed, 0xe4, 0xee, 0x56, 0xc6, 0xe3, 0xf2, 0x11, 0x8a, 0x27, 0xa3,
	0xb0, 0xc2, 0x4f, 0x3e, 0x87, 0xa9, 0xad, 0x1d, 0x76, 0xb4, 0x56, 0x22, 0x5b, 0x64, 0xd7, 0xb3,
	0x2a, 0x69, 0xce, 0x61, 0xb2, 0xd9, 0x6a, 0x25, 0x72, 0xef, 0xfb, 0x7a, 0xf4, 0xe8, 0xcb, 0xa2,
	0x38, 0x0e, 0xde, 0x58, 0x97, 0x37, 0xc0, 0x1e, 0xf4, 0x8a, 0xc8, 0xa5, 0x44, 0xf6, 0x4f, 0x22,
	0xff, 0x93, 0xf8, 0xce, 0x22, 0x41, 0x6f, 0x47, 0x82, 0xe6, 0x5d, 0xb7, 0xca, 0x61, 0xe7, 0x73,
	0xd3, 0x2a, 0x69, 0x7e, 0x0e, 0x79, 0x7a, 0x3f, 0xd7, 0x8a, 0xdf, 0x43, 0xd1, 0xea, 0xd7, 0x9a,
	0xc8, 0x79, 0x80, 0xd3, 0xe5, 0x95, 0xdc, 0x33, 0xa3, 0x0c, 0x44, 0x15, 0x6b, 0x03, 0xd9, 0x05,
	0xb0, 0x30, 0x97, 0x98, 0xf8, 0x6e, 0x51, 0x79, 0x3a, 0x1c, 0x48, 0x9c, 0x44, 0x3a, 0x1c, 0x28,
	0x11, 0xb3, 0x5f, 0xe2, 0xe5, 0x0b, 0x14, 0xab, 0xd0, 0x99, 0x3f, 0xc3, 0x6c, 0x64, 0x5f, 0x77,
	0x0a, 0x07, 0xbe, 0xd8, 0x0b, 0x10, 0x7f, 0x78, 0x7e, 0xe0, 0x46, 0x6f, 0xcb, 0xa3, 0x37, 0xe6,
	0x17, 0x76, 0xf7, 0x13, 0x00, 0x00, 0xff, 0xff, 0x87, 0xb9, 0x16, 0xdf, 0xc1, 0x01, 0x00, 0x00,
}
